### ISSUE TITLE
Is it possible to remove Cognito from AWS Kinesis Video Streams WebRTC iOS SDK

### ISSUE THREAD

**Issue by maxwell44** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#55]
Hi Guys, Is it possible to remove Cognito from AWS Kinesis Video Streams WebRTC iOS SDK ?

**Comment by alexovai** [comment]
I have a similar question. Can we use STS (temporary credentials) instead of cognito to do auth and setup webrtc in IoS ?
I have done that using js sdk (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#constructor-new-signalingclientconfig) and I want to do something similar in the IoS as well.

**Comment by codingspirit** [comment]
@maxwell44 Try https://github.com/codingspirit/amazon-kinesis-video-streams-webrtc-sdk-ios

**Comment by alexovai** [comment]
@codingspirit Thanks for the link. It is working. 

BTW, is there a way I can pass session token. I want to generate temporary credentials via STS and use it in the ios client.
Similar to js sdk.

**Comment by disa6302** [comment]
Cognito is not specific to this SDK. So, if using other authorization mechanisms, this SDK will have to be modified to use that.
