### ISSUE TITLE
Get exception"identityId shouldn't be nil" when integrated with China beijing region cognito identity pool

### ISSUE THREAD

**Issue by nimysan** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#73]
hi,

Webrtc ios sdk works fines for global cognito identity pool, but when try to integration with China beijing region Cognito identity pool. I got error like as below:

Error Domain=com.amazonaws.service.cognitoidentity.
AWSCognitoCredentialsProviderHelper
Code=0 "identityId shouldn't be nil"
UserInfo={NSLocalizedDescription=identityId shouldn't be nil}

Any idea about this? Thanks

**Comment by sirknightj** [comment]
It might be that the service endpoint might need to be overwritten since cn regions use a different endpoint domain (.com.cn) 

https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Beijing.html

https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSCore/Classes/AWSServiceConfiguration.html#/c:objc(cs)AWSServiceConfiguration(py)endpoint

Also note that the UI and documentation for creating the Cognito user pool and identity pools has recently been updated. https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producersdk-android-prerequisites.html

**Comment by sirknightj** [comment]
Closing due to no response. If this persists, please create an issue on aws-sdk-ios.
