### ISSUE TITLE
Why webrtc ios example contain authentication?

### ISSUE THREAD

**Issue by vivekgadgeon** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#84]
I checked the iOS example for webrtc and found that the user should login first to use the feature. Why the authentication is provided? Is there any way to test the feature without authentication?

**Comment by ceaglest** [comment]
I was wondering this as well. 

Could the app behave like the Amazon KVS C SDK Viewer example or the JS test page in terms of credentials? I just want to test webrtc calling between the KVS C SDK and iOS but I have to perform other setup steps that don't seem relevant to that goal.

**Comment by niyatim23** [comment]
Using AWS Cognito is generally a better choice for mobile applications due to its enhanced security, scalability, integration capabilities, and comprehensive user management features. It simplifies the implementation of secure authentication and authorization while reducing the risks associated with handling long-term AWS credentials directly in the application.
